function(listtoarg list_v arg_v)
  string(REPLACE ";" "\;" arg_v ${list_v})
endfunction(listtoarg)

function(argtolist arg_v list_v)
  string(REPLACE "\;" ";" list_v ${arg_v})
endfunction(argtolist)


function(defBI sources_l type linklibs_l linktargets_l properties_l install)
  # make arguments lists again
  foreach(varn IN LISTS "sources;linklibs;linktargets;properties")
    argtolist(${${varn}_l} ${${varn}})
  endforeach(varn)

  # get a name for the current target, based on the current directory  
  string(REPLACE "${CMAKE_SOURCE_DIR}/" "" progname_tmp ${CMAKE_CURRENT_SOURCE_DIR})
  string(REPLACE "/" "_" progname ${progname_tmp})

  if(${type} STREQUAL "EXECUTABLE")
    message("adding program \"${progname}\"")
    add_executable(${progname} ${sources})
    set(type_v "RUNTIME")
    set(destination_v "$ENV{PREFIX}/local/bin/${project}")
    set(destinationh_v "/dev/null")
  elseif(${type} STREQUAL "SHARED")
    message("adding library \"${progname}\"")
    add_library(${progname} SHARED ${sources})
    set(type_v "LIBRARY")
    set(destination_v "$ENV{PREFIX}/local/lib/${project}")
    set(destinationh_v "$ENV{PREFIX}/local/include/${project}")
  else()
    message("Target \"${progname}\" won't build anything")
    return()
  endif()
  
  foreach(loopvar IN LISTS incdir)
    target_include_directories(${progname} PUBLIC ${loopvar})
  endforeach(loopvar)
  foreach(loopvar IN LISTS properties)
    set_property(TARGET ${progname} PROPERTY ${loopvar})
  endforeach(loopvar)
  foreach(loopvar IN LISTS linklibs)
    string(REPLACE "_" "/" linklibs_d ${loopvar})
    if(${loopvar} STREQUAL " ")
      return()
    endif()
    find_library(libloc${loopvar} ${loopvar} PATHS "${CMAKE_BINARY_DIR}/${linklibs_d}")
    target_link_libraries(${progname} ${libloc${loopvar}})
  endforeach(loopvar)
  foreach(loopvar IN LISTS linktargets)
    string(REPLACE "_" "/" linklibs_d ${loopvar})
    if(${loopvar} STREQUAL " ")
      return()
    endif()
    target_link_libraries(${progname} ${loopvar})
  endforeach(loopvar)

  if(${install} MATCHES "NO.*" OR ${install} STREQUAL "OFF")
    message("Target \"${progname}\" won't install anything")
  elseif(${install} STREQUAL "ON" OR ${install} STREQUAL "INSTALL")
    message("Installing target \"${progname}\" in ${destination_v} and ${destinationh_v}")
    install(TARGETS ${progname} ${type_v} DESTINATION ${destination_v})
    install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} DESTINATION ${destination_v} FILES_MATCHING PATTERN "*.h*") 
  else()
    message("Cannot parse \"INSTALL\" argument. Target \"${progname}\" won't install anything")
  endif()
endfunction(defBI)
